# Generated by Django 5.2.1 on 2025-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motivation', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motivation', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=4)),
            ],
        ),
    ]
