# Generated by Django 5.2.1 on 2025-05-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='defeat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.heroes'),
            preserve_default=False,
        ),
    ]
