# Generated by Django 5.2.1 on 2025-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_villain_defeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='pseudonym',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villain',
            name='pseudonym',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
